In [1]:
import matplotlib.pyplot as plt
import cv2
import numpy as np
ScreenList = []

num = 2
while (num <= 2048):
    path = 'ImgLib/Gray%d.png'%num
    gray_img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    # cv2.imshow('Grayscale Image', gray_img)
    # cv2.waitKey(0)
    # cv2.destroyAllWindows()
    ScreenList.append((num, gray_img))
    if (num == 0): num += 1
    num *= 2

In [3]:
def match_template(image, template):
    result = cv2.matchTemplate(image, template, cv2.TM_CCOEFF_NORMED)
    _, max_val, _, max_loc = cv2.minMaxLoc(result)
    return max_val, max_loc

def recognize(img, templates):
    results = []
    for value, template in templates:
        max_val, max_loc = match_template(img, template)
        results.append((value, max_val, max_loc))

    best_match = max(results, key=lambda x: x[1])
    best_value, max_val, best_loc = best_match
    # print('max_val = %  .2f pattern = %d'%(max_val, best_value))
    if (max_val < 0.5): return 0
    return int(best_value)

HEIGHT = WIDTH = 150
def Handle_test(timg):
    Matrix = np.zeros((4, 4), dtype=int)
    img = cv2.resize(timg, (600, 600))
    for row in range(4):
        for col in range(4):
            resized_img = img[row * HEIGHT: (row + 1) * HEIGHT, col * WIDTH: (col + 1) * WIDTH]
            # cv2.imwrite('resized.jpg', resized_img)
            gray_img = cv2.cvtColor(resized_img, cv2.COLOR_BGR2GRAY)
            # cv2.imwrite('gray_image.jpg', gray_img)
            # cv2.imshow('Grayscale Image', gray_img)
            # cv2.waitKey(0)
            # cv2.destroyAllWindows()
            Matrix[row][col] = recognize(gray_img, ScreenList)
    return Matrix

# for i in range(1, 8):
path = 'Testset/Test7.png'
timg = cv2.imread(path)
print(Handle_test(timg))


[[   0    2   16    2]
 [   2   32   16    2]
 [   0    2 2048    2]
 [   0    0    2 1024]]
