In [1]:
######################## Modified  Tmeplate Matching ##################################

In [79]:
import matplotlib.pyplot as plt
import cv2
import numpy as np
from scipy.signal import convolve2d
import os


In [80]:
ScreenList = []

num = 2
while (num <= 2048):
    path = 'ImgLib/template_%d.png'%num
    gray_img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    # cv2.imshow('Grayscale Image', gray_img)
    # cv2.waitKey(0)
    # cv2.destroyAllWindows()
    ScreenList.append((num, gray_img))
    if (num == 0): num += 1
    num *= 2 

In [81]:
############# Template Matching ##################

############### Library Function ##############
def match_template(image, template):
    result = cv2.matchTemplate(image, template, cv2.TM_CCOEFF_NORMED)
    _, max_val, _, max_loc = cv2.minMaxLoc(result)
    return max_val, max_loc


###############  From Scratch    ################


# def match_template(image, template):
#     # Get dimensions of the image and template
#     ih, iw = image.shape
#     th, tw = template.shape

#     # Compute mean of the template and image
#     template_mean = np.mean(template)
#     image_mean = np.mean(image)

#     # Initialize result matrix
#     result = np.zeros((ih - th + 1, iw - tw + 1))

#     # Iterate over possible positions
#     for y in range(ih - th + 1):
#         for x in range(iw - tw + 1):
#             # Extract region of interest from image
#             roi = image[y:y+th, x:x+tw]

#             # Compute mean of the ROI
#             roi_mean = np.mean(roi)

#             # Compute correlation coefficient
#             numerator = np.sum((template - template_mean) * (roi - roi_mean))
#             denominator = np.sqrt(np.sum((template - template_mean) ** 2) * np.sum((roi - roi_mean) ** 2))
#             result[y, x] = numerator / denominator

#     # Get maximum correlation value and its location
#     max_val = np.max(result)
#     max_loc = np.unravel_index(np.argmax(result), result.shape)

#     return max_val, max_loc


In [82]:
def recognize(img, templates):
    results = []
    for value, template in templates:
        max_val, max_loc = match_template(img, template)
        results.append((value, max_val, max_loc))

    best_match = max(results, key=lambda x: x[1])
    best_value, max_val, best_loc = best_match
    print('max_val = %  .2f pattern = %d'%(max_val, best_value))
    if (max_val < 0.6): return 0
    return int(best_value)

In [83]:
# Directory to save images
output_dir = 'ImgLib'

HEIGHT = WIDTH = 150
def Handle_test(timg):
    Matrix = np.zeros((4, 4), dtype=int)
    img = cv2.resize(timg, (600, 600))
    for row in range(4):
        for col in range(4):
            resized_img = img[row * HEIGHT: (row + 1) * HEIGHT, col * WIDTH: (col + 1) * WIDTH]
            # cv2.imwrite('resized.jpg', resized_img)
            gray_img = cv2.cvtColor(resized_img, cv2.COLOR_BGR2GRAY)
#             cv2.imshow('Output Image', gray_img)
#             cv2.waitKey(0)
#             cv2.destroyAllWindows()

#              Generate a unique filename for each image
#             filename = os.path.join(output_dir, f'output_image_{row}_{col}.jpg')
#             # Write the image to the file
#             cv2.imwrite(filename, gray_img)
            
            Matrix[row][col] = recognize(gray_img, ScreenList)
    return Matrix

# for i in range(1, 8):
path = 'test_img/newtest5.jpg'
timg = cv2.imread(path)
print(Handle_test(timg))


max_val =  0.49 pattern = 8
max_val =  0.94 pattern = 2
max_val =  0.87 pattern = 16
max_val =  0.95 pattern = 2
max_val =  0.90 pattern = 2
max_val =  0.84 pattern = 32
max_val =  0.83 pattern = 16
max_val =  0.91 pattern = 2
max_val =  0.38 pattern = 128
max_val =  0.85 pattern = 2
max_val =  0.76 pattern = 2048
max_val =  0.85 pattern = 2
max_val =  0.37 pattern = 128
max_val =  0.43 pattern = 8
max_val =  0.80 pattern = 2
max_val =  0.51 pattern = 1024
[[   0    2   16    2]
 [   2   32   16    2]
 [   0    2 2048    2]
 [   0    0    2    0]]


In [19]:

###################### reszie image ##################
import cv2
num=128
while num <=2048:
    # Read the image
    image = cv2.imread(f"ImgLib/template_{num}.png")

    # Resize the image to 100x100 pixels
    resized_image = cv2.resize(image, (60, 60))

    cv2.imwrite(f"newLib/template_{num}.png",resized_image)
    num*=2
    # Display the resized image
#     cv2.imshow('Resized Image', resized_image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()


In [17]:
# Read the image
image = cv2.imread("ImgLib/template_16.png")

# Resize the image to 100x100 pixels
resized_image = cv2.resize(image, (60, 60))

cv2.imwrite("newLib/template_16.png",resized_image)

True